### ISSUE TITLE
a thread_local error on mac?

### ISSUE THREAD

**Issue by huahang** [facebook/folly#217] opened 2015-05-30 01:36 UTC
./../folly/experimental/fibers/FiberManager-inl.h:457:10: error: thread-local
          storage is not supported for the current target
      static thread_local T t;
             ^
    1 error generated.

It seems build on Mac is broken?

**Comment by djwatson** [comment] 2015-06-09 18:10
Yea I think there are several issues on mac builds besides just this one.  We currently don't have a continuous build set up for macs - we're happy to accept patches, but until we get a build, it is unfortunately likely to keep breaking.

**Comment by bowlofstew** [comment] 2015-06-10 22:02
I just pulled down master/compiled on a new machine and don't see that issue.

sw_vers
ProductName:	Mac OS X
ProductVersion:	10.10.3
BuildVersion:	14D2134

**Comment by bowlofstew** [comment] 2015-06-10 22:09
I reproduced the same behavior from master with:

sw_vers
ProductName:	Mac OS X
ProductVersion:	10.10.3
BuildVersion:	14D2134

clang --version
Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)
Target: x86_64-apple-darwin14.3.0
Thread model: posix

**Comment by sgolemon** [comment] 2015-06-24 19:39
Looks like 36ca845043259977fac1e8cddec7427d711e1126 (which landed shortly after this issue was opened) fixes this.

Please reopen with new pastes if you're still getting an error.

**Closed by sgolemon** 2015-06-24 19:39 UTC
