### ISSUE TITLE
Try setting folly up on ubuntu 17.04 and let me know.. 

### ISSUE THREAD

**Issue by arsalan993** [facebook/folly#767] opened 2018-02-08 10:12 UTC
when i make _build directory inside folly-master folder i get error
`-- Setting FOLLY_USE_SYMBOLIZER: ON
CMake Error at CMakeLists.txt:104 (list):
  list sub-command REMOVE_ITEM requires list to be present.

CMake Error at CMakeLists.txt:109 (list):
  list sub-command REMOVE_ITEM requires list to be present.

-- Configuring incomplete, errors occurred!
See also "/home/test/Downloads/folly-master/_build/CMakeFiles/CMakeOutput.log".
See also "/home/test/Downloads/folly-master/_build/CMakeFiles/CMakeError.log".
`

**Comment by arsalan993** [comment] 2018-02-08 10:13
and When i make _build directory inside folly-master/folly/ directory i get this error
`CMake Error at CMakeLists.txt:7 (apply_folly_compile_options_to_target):
  Unknown CMake command "apply_folly_compile_options_to_target".


-- Configuring incomplete, errors occurred!
See also "/home/test/Downloads/folly-master/folly/_build/CMakeFiles/CMakeOutput.log".
`

**Comment by shixiao** [comment] 2018-03-04 04:43
Did you install all the dependencies on Ubuntu via `apt-get` (https://github.com/facebook/folly#ubuntu-1604-lts)? After that, try removing `CMakeCache.txt`, and running `cd _build && cmake configure ..`

**Comment by shixiao** [comment] 2018-03-04 04:51
Duplicate of #766.

**Comment by shixiao** [comment] 2018-03-04 04:52
Duplicate of #766.

**Comment by zhshw** [comment] 2018-03-04 17:04
@arsalan993  CMakeLists.txt file   "/build/"  match remove files from list, if you path like "/home/xxx/build/folly"  all files will be match to remove！

**Comment by yfeldblum** [comment] 2023-01-07 07:13
Closing this issue because it is too old.

**Closed by yfeldblum** 2023-01-07 07:13 UTC
