### ISSUE TITLE
cannot to compile folly on ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by LeeBY2016** [facebook/folly#803] opened 2018-03-14 08:56 UTC
I want to compile folly and other related libs for Toch7 in the virtual environment on Ubuntu 16.04 LTS.
However, folly always failed with the error:
```
/bin/bash ../../../libtool  --tag=CXX   --mode=link g++  -std=gnu++1y -g -O2 -lboost_context -lboost_program_options -lboost_thread -lboost_filesystem -lboost_system -lboost_regex -lpthread -lboost_chrono  -lssl -lcrypto  -o logging_example main.o libfollylogging_example.la -lbz2 -llzma -lz -lsnappy -llz4 -liberty -ldl -levent -ldouble-conversion -lglog -lgflags 
libtool: link: g++ -std=gnu++1y -g -O2 -o .libs/logging_example main.o  ./.libs/libfollylogging_example.a /home/miaomiaolee/Software/recognition/folly/folly/experimental/logging/.libs/libfollylogging.so /home/miaomiaolee/Software/recognition/folly/folly/.libs/libfolly.so -lboost_context -lboost_program_options -lboost_thread -lboost_filesystem -lboost_system -lboost_regex -lpthread -lboost_chrono -lssl -lcrypto -lbz2 -llzma -lz -lsnappy -llz4 -liberty -ldl -levent -ldouble-conversion -lglog -lgflags
/home/miaomiaolee/Software/recognition/folly/folly/.libs/libfolly.so: undefined reference to `boost::re_detail_106600::put_mem_block(void*)'
/home/miaomiaolee/Software/recognition/folly/folly/.libs/libfolly.so: undefined reference to `boost::re_detail_106600::get_default_error_string(boost::regex_constants::error_type)'
/home/miaomiaolee/Software/recognition/folly/folly/.libs/libfolly.so: undefined reference to `boost::re_detail_106600::perl_matcher<char const*, std::allocator<boost::sub_match<char const*> >, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::construct_init(boost::basic_regex<char, boost::regex_traits<char, boost::cpp_regex_traits<char> > > const&, boost::regex_constants::_match_flags)'
/home/miaomiaolee/Software/recognition/folly/folly/.libs/libfolly.so: undefined reference to `boost::re_detail_106600::get_mem_block()'
/home/miaomiaolee/Software/recognition/folly/folly/.libs/libfolly.so: undefined reference to `boost::re_detail_106600::verify_options(unsigned int, boost::regex_constants::_match_flags)'
/home/miaomiaolee/Software/recognition/folly/folly/.libs/libfolly.so: undefined reference to `boost::re_detail_106600::cpp_regex_traits_implementation<char>::transform(char const*, char const*) const'
/home/miaomiaolee/Software/recognition/folly/folly/.libs/libfolly.so: undefined reference to `boost::re_detail_106600::raise_runtime_error(std::runtime_error const&)'
/home/miaomiaolee/Software/recognition/folly/folly/.libs/libfolly.so: undefined reference to `boost::re_detail_106600::cpp_regex_traits_implementation<char>::transform_primary(char const*, char const*) const'
/home/miaomiaolee/Software/recognition/folly/folly/.libs/libfolly.so: undefined reference to `boost::re_detail_106600::perl_matcher<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::construct_init(boost::basic_regex<char, boost::regex_traits<char, boost::cpp_regex_traits<char> > > const&, boost::regex_constants::_match_flags)'
collect2: error: ld returned 1 exit status
Makefile:421: recipe for target 'logging_example' failed
make[4]: *** [logging_example] Error 1
make[4]: Leaving directory '/home/miaomiaolee/Software/recognition/folly/folly/experimental/logging/example'
Makefile:598: recipe for target 'all-recursive' failed
make[3]: *** [all-recursive] Error 1
make[3]: Leaving directory '/home/miaomiaolee/Software/recognition/folly/folly/experimental/logging'
Makefile:405: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/home/miaomiaolee/Software/recognition/folly/folly/experimental'
Makefile:2342: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/miaomiaolee/Software/recognition/folly/folly'
Makefile:1347: recipe for target 'all' failed
make: *** [all] Error 2

```
The procedure is:
`workon ENV`
install the libs for folly.
```
cd /folly/folly
autoreconf -ivf
./configure
make
```

No matter "./configure" change to 
```
./configure --with-boost-libdir=/usr/local/lib 
./configure --with-boost=/usr/local/lib
./configure --with-boost=/usr/local

```
any ideas?

**Comment by mrigeshcmu** [comment] 2018-03-29 00:39
I had this when using gcc 4.9, but my build succeeded using gcc 6. I believe you may need `gcc >= 5`.

**Comment by wekesa01** [comment] 2018-03-29 22:38
I have the **exact error codes and messages**, using ubuntu 16,04 
gcc version 5.4.0 boost 1.66  compiled with ./b2 cxxflags=-std=c++14.  
installed with ./b2 cxxflags=-std=c++14 install . 
then built and installed folly.
upon building proxygen I bump into these weird linker errors

**Comment by LeeBY2016** [comment] 2018-04-01 12:52
The version of gcc I used is 5.4.0. maybe the version of gcc must be >=6 ?

**Comment by tdargahi** [comment] 2018-04-09 22:37
Ubuntu 16.0.4  gcc version 5.4
This works for me with flags set as following. I think the problem is that boost is installed at /usr/local/lib
./configure CPPFLAGS="-I/usr/local/include" LDFLAGS="-L/usr/local/lib"
make

**Comment by yfeldblum** [comment] 2023-01-02 03:18
Closing this issue because it is too old, and because folly no longer supports Ubuntu 16.04.

**Closed by yfeldblum** 2023-01-02 03:18 UTC
