### ISSUE TITLE
make check fail with ubuntu 16.04

### ISSUE THREAD

**Issue by anoidgit** [facebook/folly#533] opened 2016-12-21 12:32 UTC
make[3]: Entering directory '/media/Storage/workspace/folly/folly/test'
make[3]: *** No rule to make target 'gtest-1.7.0/src/gtest-all.cc', needed by 'gtest-1.7.0/src/libfollytestmain_la-gtest-all.lo'。 停止。
make[3]: Leaving directory '/media/Storage/workspace/folly/folly/test'
Makefile:2550: recipe for target 'check-am' failed
make[2]: *** [check-am] Error 2
make[2]: Leaving directory '/media/Storage/workspace/folly/folly/test'
Makefile:1854: recipe for target 'check-recursive' failed
make[1]: *** [check-recursive] Error 1
make[1]: Leaving directory '/media/Storage/workspace/folly/folly/test'
Makefile:1765: recipe for target 'check-recursive' failed
make: *** [check-recursive] Error 1

**Comment by rouniuyizu** [comment] 2016-12-30 04:21
### I had the same issue but once you manully downloaded googletest 1.7 and unzipped it (need rename to gtest-1.7.0) into that folder, the issue "No rule..." went away, but I had another one popped up as following:
=================================================
g++ -DHAVE_CONFIG_H   -I../.. -pthread -I/usr/include  -Igtest-1.7.0/include  -std=gnu++1y -g -O2 -MT FunctionRefTest.o -MD -MP -MF $depbase.Tpo -c -o FunctionRefTest.o FunctionRefTest.cpp &&\
mv -f $depbase.Tpo $depbase.Po
In file included from gtest-1.7.0/include/gtest/gtest.h:58:0,
                 from ../../folly/portability/GTest.h:32,
                 from FunctionRefTest.cpp:20:
FunctionRefTest.cpp: In member function ‘virtual void FunctionRef_DefaultConstructAndAssign_Test::TestBody()’:
gtest-1.7.0/include/gtest/internal/gtest-internal.h:1111:44: error: no matching function for call to ‘testing::AssertionResult::AssertionResult(folly::FunctionRef<int(int, int)>&)’
       ::testing::AssertionResult(expression)) \
                                            ^
gtest-1.7.0/include/gtest/gtest.h:1915:3: note: in expansion of macro ‘GTEST_TEST_BOOLEAN_’
   GTEST_TEST_BOOLEAN_(condition, #condition, false, true, \
   ^
FunctionRefTest.cpp:146:3: note: in expansion of macro ‘EXPECT_TRUE’
   EXPECT_TRUE(fref);
   ^
In file included from ../../folly/portability/GTest.h:32:0,
                 from FunctionRefTest.cpp:20:
gtest-1.7.0/include/gtest/gtest.h:262:12: note: candidate: testing::AssertionResult::AssertionResult(bool)
   explicit AssertionResult(bool success) : success_(success) {}
            ^
gtest-1.7.0/include/gtest/gtest.h:262:12: note:   no known conversion for argument 1 from ‘folly::FunctionRef<int(int, int)>’ to ‘bool’
gtest-1.7.0/include/gtest/gtest.h:260:3: note: candidate: testing::AssertionResult::AssertionResult(const testing::AssertionResult&)
   AssertionResult(const AssertionResult& other);
   ^
gtest-1.7.0/include/gtest/gtest.h:260:3: note:   no known conversion for argument 1 from ‘folly::FunctionRef<int(int, int)>’ to ‘const testing::AssertionResult&’
Makefile:1842: recipe for target 'FunctionRefTest.o' failed
make[3]: *** [FunctionRefTest.o] Error 1
make[3]: Leaving directory '/tmp/fblualib-build.UZCtnC/folly/folly/test'
Makefile:2590: recipe for target 'check-am' failed
make[2]: *** [check-am] Error 2
make[2]: Leaving directory '/tmp/fblualib-build.UZCtnC/folly/folly/test'
Makefile:1880: recipe for target 'check-recursive' failed
make[1]: *** [check-recursive] Error 1
make[1]: Leaving directory '/tmp/fblualib-build.UZCtnC/folly/folly/test'
Makefile:1775: recipe for target 'check-recursive' failed
make: *** [check-recursive] Error 1

**Comment by anoidgit** [comment] 2017-01-01 04:36
Thank you for your help, and I think maybe google-test have changed the release after they build folly. @rouniuyizu

**Comment by excalibur-sa** [comment] 2017-01-06 06:19
any solution for this problem？“I had the same issue but once you manully downloaded googletest 1.7 and unzipped it (need rename to gtest-1.7.0) into that folder, the issue "No rule..." went away, but I had another one popped up as following”. If you know available version of folly and gtest, please tell me. Thanks!

**Comment by QunxingHu** [comment] 2017-01-12 04:45
1. Firstly,  download  googletest1.7 and unzip it , rename to gtest1.7.0 into the folder.  This can solve the issue `No rule ...`.
2.  As @rouniuyizu commented above, the second issue will show up during `make check`, I found the temporary solution to this problem. This error was caused by `FunctionRefTest.cpp:146` , the reason i guess is that google has changed the `EXPECT_TRUE` rule, the rule to covert the conditions to BOOL in `EXPECT_TRUE` might be stringent. So, we can just Comment out or delete line `FunctionRefTest.cpp:146` as obviously this testcase will pass.  @excalibur-sa

**Comment by shindo** [comment] 2017-01-12 07:14
> 2. As @rouniuyizu commented above, the second issue will show up during make check, I found the temporary solution to this problem. This error was caused by FunctionRefTest.cpp:146 , the reason i guess is that google has changed the EXPECT_TRUE rule, the rule to covert the conditions to BOOL in EXPECT_TRUE might be stringent. So, we can just Comment out or delete line FunctionRefTest.cpp:146 as obviously this testcase will pass. @excalibur-sa

Or you could just explicitly cast `fref` to bool (because `FunctionRef` has `explicit operator bool()`) the same way as this was done for `Function`: https://github.com/facebook/folly/commit/f70249c03acbf2e0d4449d6e74b8ab6cae206b28

**Comment by Orvid** [comment] 2018-09-20 20:07
Support for the autotools build has been removed in favor of CMake, so I'm closing out this issue.

**Closed by Orvid** 2018-09-20 20:07 UTC
