### ISSUE TITLE
Initial tests for folly::fbvector show that it is slower than std::vector ?

### ISSUE THREAD

**Issue by pmalek** [facebook/folly#379] opened 2016-03-23 23:07 UTC
I have downloaded folly's source code and compiled it and started working with it and I came to those exemplar benchmarks at https://github.com/facebook/folly/blob/master/folly/docs/Benchmark.md and I changed them to:

```
#include <folly/Benchmark.h>
#include <folly/Foreach.h>
#include <folly/FBVector.h>
#include <vector>

constexpr int COUNT = 1000;

BENCHMARK(insertBackVector)
{
  std::vector<int> v;
  v.reserve(COUNT);
  FOR_EACH_RANGE(i, 0, COUNT)
  {
    v.insert(v.end(), i);
  }
}

BENCHMARK_RELATIVE(insertBackFBVector)
{
  folly::fbvector<int> fbv;
  fbv.reserve(COUNT);
  FOR_EACH_RANGE(i, 0, COUNT)
  {
    fbv.insert(fbv.end(), i);
  }
}

BENCHMARK_DRAW_LINE();

BENCHMARK(insertFrontVector)
{
  std::vector<int> v;
  v.reserve(COUNT);
  FOR_EACH_RANGE(i, 0, COUNT)
  {
    v.insert(v.begin(), i);
  }
}

BENCHMARK_RELATIVE(insertFrontFBVector)
{
  folly::fbvector<int> fbv;
  fbv.reserve(COUNT);
  FOR_EACH_RANGE(i, 0, COUNT)
  {
    fbv.insert(fbv.begin(), i);
  }
}

int main()
{
  folly::runBenchmarks();
}
```

And I have received the following results for different optimisation levels:

```
~/programming/c/folly_tests/benchmark1 » g++ -O3 --std=c++14 -L/home/USER/programming/c/folly/lib/ -Wl,-rpath=/home/USER/programming/c/folly/lib/  main.cpp -lfollybenchmark -lfolly -lglog -lgflags -I/home/USER/programming/c/folly/include/ -o main && ./main                  
============================================================================
main.cpp                                        relative  time/iter  iters/s
============================================================================
insertBackVector                                             1.88us  531.34K
insertBackFBVector                                37.31%     5.04us  198.23K
----------------------------------------------------------------------------
insertFrontVector                                           41.48us   24.11K
insertFrontFBVector                               96.52%    42.98us   23.27K
============================================================================
------------------------------------------------------------
~/programming/c/folly_tests/benchmark1 » g++ -O2 --std=c++14 -L/home/USER/programming/c/folly/lib/ -Wl,-rpath=/home/USER/programming/c/folly/lib/  main.cpp -lfollybenchmark -lfolly -lglog -lgflags -I/home/USER/programming/c/folly/include/ -o main && ./main
============================================================================
main.cpp                                        relative  time/iter  iters/s
============================================================================
insertBackVector                                             2.46us  407.02K
insertBackFBVector                                46.18%     5.32us  187.94K
----------------------------------------------------------------------------
insertFrontVector                                           44.91us   22.27K
insertFrontFBVector                              104.26%    43.08us   23.21K
============================================================================
------------------------------------------------------------
~/programming/c/folly_tests/benchmark1 » g++ -O1 --std=c++14 -L/home/USER/programming/c/folly/lib/ -Wl,-rpath=/home/USER/programming/c/folly/lib/  main.cpp -lfollybenchmark -lfolly -lglog -lgflags -I/home/USER/programming/c/folly/include/ -o main && ./main
============================================================================
main.cpp                                        relative  time/iter  iters/s
============================================================================
insertBackVector                                             2.41us  414.92K
insertBackFBVector                                36.26%     6.65us  150.44K
----------------------------------------------------------------------------
insertFrontVector                                           45.39us   22.03K
insertFrontFBVector                              103.33%    43.92us   22.77K
============================================================================
------------------------------------------------------------
~/programming/c/folly_tests/benchmark1 » g++ -g --std=c++14 -L/home/USER/programming/c/folly/lib/ -Wl,-rpath=/home/USER/programming/c/folly/lib/  main.cpp -lfollybenchmark -lfolly -lglog -lgflags -I/home/USER/programming/c/folly/include/ -o main && ./main
============================================================================
main.cpp                                        relative  time/iter  iters/s
============================================================================
insertBackVector                                            42.65us   23.45K
insertBackFBVector                                67.68%    63.02us   15.87K
----------------------------------------------------------------------------
insertFrontVector                                          152.79us    6.54K
insertFrontFBVector                              155.96%    97.97us   10.21K
============================================================================
------------------------------------------------------------
~/programming/c/folly_tests/benchmark1 » g++ -O3 --std=c++14 -L/home/USER/programming/c/folly/lib/ -Wl,-rpath=/home/USER/programming/c/folly/lib/  main.cpp -lfollybenchmark -lfolly -lglog -lgflags -I/home/USER/programming/c/folly/include/ -o main && ./main
============================================================================
main.cpp                                        relative  time/iter  iters/s
============================================================================
insertBackVector                                             1.86us  537.57K
insertBackFBVector                                36.88%     5.04us  198.26K
----------------------------------------------------------------------------
insertFrontVector                                           41.43us   24.14K
insertFrontFBVector                               96.37%    42.99us   23.26K
============================================================================
```

From those results we can clearly see that `folly::fbvector` is only faster in few cases where we push on the front and looses all the cases with `std::vector` at pushing at the back of the container.

Am I missing something here?

Ubuntu 14.04, gcc 5.3.1, x86_64

folly version checked: v0.57.0 and master

**Comment by snarkmaster** [comment] 2016-03-24 21:33
@pmalek, I've assigned this to @Gownta who knows this code, but I'll just assume that your benchmarks are representative for now. The caveats are: 
 - you are benchmarking only very small vectors (L1 cache small) only of ints, 
 - the docs claim `fbvector` is tuned for relocatable types (`IsRelocatable<int>` **should** be true, I haven't checked), and
 - `jemalloc` (were you using that?)

If `std::vector` is faster across the board, this is actually a great result! When you write a fast drop-in replacement (as this was, years ago) for an `std::` construct, you hope that the upstream compilers and standard libraries will implement similar tricks, so that you can delete your custom code and have less stuff to maintain. I would be pleased if gcc-5.3.1 reached that point.

Again, I hope that @Gownta will respond authoritatively.

**Comment by Gownta** [comment] 2016-03-25 18:44
@pmalek, thanks so much for this analysis!

I ran your benchmark code, and saw similar results in my setup. Since insert-front is faster for both you and me, I ignored it for the rest of my analysis.

`insert(self.end(), value)` is the same as `push_back(value)`, the latter being the canonical way of appending an element to a vector. I checked our benchmarks for push_back, and they seem to be slightly faster than std::vector.

However, insert is the correct function to call when appending multiple elements to the back of a vector. I modified your benchmark code to test the speed of multiple back insertions, and I did notice that our insert-at-back code is fundamentally slower for the multiple elements case (as well as for the single element case).

(I also tested insert-in-middle. Vectors are the wrong datastructure for inserting into the middle, but we shouldn't be too much slower than std::vector. Fortunately, all of my analysis on insert-middle looks to be on par with std::vector.)

Back to insert-back. It's slower. I dug into why.
- Tests should be run with -DNDEBUG, to disable all of the debug asserts (as is the norm for production code)
- There is a guard for internal references in the insert code. Technically, the standard allows for undefined behavior in this case, but we have a preference to catch bad code early. Removing this code brings the benchmarks closer together, but there is still a gap for insert-at-back.
- Looking at std::vector code, there is a special-case code path for insertion at the back of the array.

My follow-up: I'll write a special case function to deal with insertion at the back of the array. This is a common operation for multi-element-insert, and should incidentally make the push-back-like insert case faster too. This special case should remove the need to our internal reference guard, and several of the asserts.

**Comment by Gownta** [comment] 2016-03-30 16:55
I've landed a commit which speeds up back-insertion by about 4x. My benchmarks still show a slight speed difference, but not the gaping difference you observed in this issue.

https://github.com/facebook/folly/commit/8063649a1af220a9cbd12ae46cd01ffaa4adb323

Thanks for reporting this!

**Closed by Gownta** 2016-03-30 16:55 UTC

**Comment by pmalek** [comment] 2016-03-30 19:33
Thanks to you @Gownta. Although I have spotted this one it is you who wrote the patch :)

Feels good to contribute at least a tiny bit to an open source project.

**Comment by pmalek** [comment] 2016-04-12 17:59
I know that this is closed now but these are my results that I have received  when I compile this version of folly https://github.com/facebook/folly/commit/54b83bda19021805ed9a1d62c27c875fd8ff7589


I have modified the tests file so that we only take `push_back()` and `insert()` (at back) operations as they are the most important in vector:

```
#include <folly/Benchmark.h>
#include <folly/Foreach.h>
#include <folly/FBVector.h>
#include <vector>

constexpr int COUNT = 300000;

BENCHMARK(insertBackVector)
{
  std::vector<int> v;
  v.reserve(COUNT);
  FOR_EACH_RANGE(i, 0, COUNT)
  {
    v.insert(v.end(), i);
  }
}

BENCHMARK_RELATIVE(insertBackFBVector)
{
  folly::fbvector<int> fbv;
  fbv.reserve(COUNT);
  FOR_EACH_RANGE(i, 0, COUNT)
  {
    fbv.insert(fbv.end(), i);
  }
}

BENCHMARK_DRAW_LINE();

BENCHMARK(pushBackVector)
{
  std::vector<int> v;
  v.reserve(COUNT);
  FOR_EACH_RANGE(i, 0, COUNT)
  {
    v.push_back(i);
  }
}

BENCHMARK_RELATIVE(pushBackFBVector)
{
  folly::fbvector<int> fbv;
  fbv.reserve(COUNT);
  FOR_EACH_RANGE(i, 0, COUNT)
  {
    fbv.push_back(i);
  }
}

int main()
{
  folly::runBenchmarks();
}
```

and there are the results that I have received:

```
~/programming/c/folly_tests/benchmark1 » g++ -DNDEBUG -O3 --std=c++14 -L/home/USER/programming/c/folly/lib/ main.cpp -Wl,-Bstatic -lunwind -llzma -pthread -lfolly -lfollybenchmark -lfolly -lglog -lgflags -lboost_regex -ldouble-conversion -Wl,-Bdynamic -I/home/USER/programming/c/folly/include/ -o main && ./main                                                               
============================================================================
main.cpp                                        relative  time/iter  iters/s
============================================================================
insertBackVector                                           581.29us    1.72K
insertBackFBVector                               210.29%   276.42us    3.62K
----------------------------------------------------------------------------
pushBackVector                                             158.00us    6.33K
pushBackFBVector                                  27.97%   564.84us    1.77K
============================================================================
------------------------------------------------------------
~/programming/c/folly_tests/benchmark1 » g++ -v                                                                                                                 USER@icanseeyou [19:52:30]
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/5/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 5.3.0-3ubuntu1~14.04' --with-bugurl=file:///usr/share/doc/gcc-5/README.Bugs --enable-languages=c,ada,c++,java,go,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-5 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=gcc4-compatible --disable-libstdcxx-dual-abi --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-5-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-5-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-5-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 5.3.0 20151204 (Ubuntu 5.3.0-3ubuntu1~14.04) 
------------------------------------------------------------
~/programming/c/folly_tests/benchmark1 » clang++ -DNDEBUG -O3 --std=c++14 -L/home/USER/programming/c/folly/lib/ main.cpp -Wl,-Bstatic -lunwind -llzma -pthread -lfolly -lfollybenchmark -lfolly -lglog -lgflags -lboost_regex -ldouble-conversion -Wl,-Bdynamic -I/home/USER/programming/c/folly/include/ -o main && ./main
============================================================================
main.cpp                                        relative  time/iter  iters/s
============================================================================
insertBackVector                                           475.42us    2.10K
insertBackFBVector                                32.51%     1.46ms   683.91
----------------------------------------------------------------------------
pushBackVector                                             158.12us    6.32K
pushBackFBVector                                  33.27%   475.22us    2.10K
============================================================================
------------------------------------------------------------
~/programming/c/folly_tests/benchmark1 » clang++ -v                                                                                                             USER@icanseeyou [19:52:39]
Ubuntu clang version 3.6.0-2ubuntu1~trusty1 (tags/RELEASE_360/final) (based on LLVM 3.6.0)
Target: x86_64-pc-linux-gnu
Thread model: posix
Found candidate GCC installation: /usr/bin/../lib/gcc/i686-linux-gnu/5.3.0
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8.5
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9.3
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/5.3.0
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/5.3.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8.5
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9.3
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5.3.0
Selected GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/5.3.0
Candidate multilib: .;@m64
Selected multilib: .;@m64
```

**Comment by Gownta** [comment] 2016-04-14 16:15
Our benchmarks show that push_back is comparable across both vectors. This isn't to say that either of our benchmark code in incorrect, merely that benchmarks are fragile things. For the insert case, I was capable of reproducing the speed difference, which is why I could make improvements; but for this performance difference I would be running blind, making changes and hoping they made your setup faster.

If you'd like to put up a patch that makes push_back faster on your system, I would be happy to review the code and make sure that it isn't slower on ours :) That way we'd be sure that the patch is actually a performance win on both systems.
