### ISSUE TITLE
Folly not building with gcc5 

### ISSUE THREAD

**Issue by VictorRodriguez** [facebook/folly#208] opened 2015-05-19 16:45 UTC
HI I am trying to build fully with gcc5. However I am having the following problem: 

./../folly/Traits.h: In substitution of ‘template<class RHS, RHS rhs, class LHS> bool folly::detail::less_than_impl(typename std::enable_if<((rhs <= std::numeric_limits<_UIntType>::max()) && (rhs > std::numeric_limits<_UIntType>::min())), LHS>::type) [with RHS = long int; RHS rhs = -9223372036854775808l; LHS = bool]’:
./../folly/Traits.h:412:4:   required from ‘bool folly::less_than(LHS) [with RHS = long int; RHS rhs = -9223372036854775808l; LHS = bool]’
./../folly/Conv.h:110:5:   required from ‘typename std::enable_if<((std::is_integral<_Tp2>::value && std::is_integral<_Tp>::value) && (! std::is_same< <template-parameter-1-1>, <template-parameter-1-2> >::value)), Tgt>::type folly::to(const Src&) [with Tgt = long int; Src = bool; typename std::enable_if<((std::is_integral<_Tp2>::value && std::is_integral<_Tp>::value) && (! std::is_same< <template-parameter-1-1>, <template-parameter-1-2> >::value)), Tgt>::type = long int]’
./../folly/dynamic-inl.h:759:30:   required from ‘T folly::dynamic::asImpl() const [with T = long int]’
./../folly/dynamic-inl.h:392:68:   required from here
./../folly/Traits.h:325:10: warning: comparison of constant ‘-9223372036854775808l’ with boolean expression is always true [-Wbool-compare]
     (rhs <= std::numeric_limits<LHS>::max()
          ^
./../folly/Traits.h:326:14: warning: comparison of constant ‘-9223372036854775808l’ with boolean expression is always false [-Wbool-compare]
       && rhs > std::numeric_limits<LHS>::min()),
              ^
‘
Internal compiler error: Error reporting routines re-entered.
0x624411 build_new_op_1
	../../gcc-5.1.0/gcc/cp/call.c:5691
0x624dbe build_new_op(unsigned int, tree_code, int, tree_node*, tree_node*, tree_node*, tree_node**, int)
	../../gcc-5.1.0/gcc/cp/call.c:5750
0x6c058e build_x_binary_op(unsigned int, tree_code, tree_node*, tree_code, tree_node*, tree_code, tree_node**, int)
	../../gcc-5.1.0/gcc/cp/typeck.c:3803
0x64b49f tsubst_copy_and_build(tree_node*, tree_node*, int, tree_node*, bool, bool)
	../../gcc-5.1.0/gcc/cp/pt.c:14776
0x652daa tsubst_expr
	../../gcc-5.1.0/gcc/cp/pt.c:14398
0x653d4c tsubst_template_arg
	../../gcc-5.1.0/gcc/cp/pt.c:9707
0x6587c9 tsubst_template_args
	../../gcc-5.1.0/gcc/cp/pt.c:10257
0x658cf4 tsubst_aggr_type
	../../gcc-5.1.0/gcc/cp/pt.c:10454
0x64d5d9 tsubst(tree_node*, tree_node*, int, tree_node*)
	../../gcc-5.1.0/gcc/cp/pt.c:12418
0x686770 dump_template_bindings
	../../gcc-5.1.0/gcc/cp/error.c:369
0x686770 dump_substitution
	../../gcc-5.1.0/gcc/cp/error.c:1448
0x688347 decl_to_string
	../../gcc-5.1.0/gcc/cp/error.c:2910
0x688347 cp_printer
	../../gcc-5.1.0/gcc/cp/error.c:3494
0x1091eaf pp_format(pretty_printer*, text_info*)
	../../gcc-5.1.0/gcc/pretty-print.c:613
0x1092670 pp_format_verbatim(pretty_printer*, text_info*)
	../../gcc-5.1.0/gcc/pretty-print.c:672
0x1092755 pp_verbatim(pretty_printer*, char const*, ...)
	../../gcc-5.1.0/gcc/pretty-print.c:875
0x68246a print_instantiation_full_context
	../../gcc-5.1.0/gcc/cp/error.c:3273
0x68246a maybe_print_instantiation_context
	../../gcc-5.1.0/gcc/cp/error.c:3417
0x687493 cp_diagnostic_starter
	../../gcc-5.1.0/gcc/cp/error.c:3109
0x108f209 diagnostic_report_diagnostic(diagnostic_context*, diagnostic_info*)
	../../gcc-5.1.0/gcc/diagnostic.c:866
Please submit a full bug report,
with preprocessed source if appropriate.
Please include the complete backtrace with any bug report.
See <http://gcc.gnu.org/bugs.html> for instructions.
Makefile:1387: recipe for target 'File.lo' failed
make[2]: *** [File.lo] Error 1
Makefile:1387: recipe for target 'dynamic.lo' failed
make[2]: *** [dynamic.lo] Error 1
Makefile:1387: recipe for target 'String.lo' failed
make[2]: Leaving directory '/builddir/build/BUILD/folly-0.38.0/folly'
make[2]: *** [String.lo] Error 1
Makefile:1448: recipe for target 'all-recursive' failed
make[1]: Leaving directory '/builddir/build/BUILD/folly-0.38.0/folly'
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
Makefile:903: recipe for target 'all' failed

This is my config  : 

%build                                                                          
cd folly                                                                        
%reconfigure --disable-static                                                   
make V=1  %{?_smp_mflags}   

Is there any effort for gcc 5 on this ?

**Comment by paulbiss** [comment] 2015-05-19 17:36
We've had a few people look at it. We're still running 4.8 internally. Eventually we're going to need to get it working but it isn't a high priority right now. Last I checked a few contributors had gotten it to build but were experiencing crashes with it.

**Comment by paulbiss** [comment] 2015-05-19 17:37
Oops, deleted my comment, thought I was in a different repo, my apologies.

**Comment by VictorRodriguez** [comment] 2015-05-19 18:02
Here is the comment: 
We've had a few people look at it. We're still running 4.8 internally. Eventually we're going to need to get it working but it isn't a high priority right now. Last I checked a few contributors had gotten it to build but were experiencing crashes with it.

**Comment by VictorRodriguez** [comment] 2015-05-22 17:34
@paulbiss  if you have a patch ( or a series of them ) I can test and send feedback

**Comment by paulbiss** [comment] 2015-05-22 17:35
Sorry about that, the comment was in reference to hhvm. I'm actually not sure what the status of folly with gcc5 is.

**Comment by VictorRodriguez** [comment] 2015-05-22 18:14
np @paulbiss  is there any IRC chanell or mailing list I could work with. I really need folly to work with gcc5 :) and I am willing to help . I just need to work with the folly team for some guidance

**Comment by jrobeson** [comment] 2015-05-24 08:15
@paulbiss : fedora 22 ships with gcc 5, so i currently can't build packages for it.

**Comment by xnox** [comment] 2015-05-26 11:36
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=65882

Trying patch from: https://gcc.gnu.org/ml/gcc-patches/2015-04/msg01558.html

**Comment by xnox** [comment] 2015-05-27 12:34
@jrobeson the pull request above ^ fixes this for me with gcc 5.1.

**Comment by lbrandy** [comment] 2015-06-05 18:02
I just want to say on the general issue: we're going to prioritize getting folly onto gcc 5+ eventually but not quite yet. I'll accept patches if they are clean but full support will have to wait a bit since we're not really setup to keep it working.

**Comment by VictorRodriguez** [comment] 2015-06-05 18:31
The patches @xnox send fix this issue and makes folly work fine. FOr me the bug could be closed with that patches

**Comment by sgolemon** [comment] 2015-06-23 22:13
I'm going to close this issue because it LOOKS like it got resolved with one of the many PRs I merged recently.  I've also confirmed that it builds for me on Ubuntu using gcc-5.1 there.

Please reopen if this is not in fact the case.

**Closed by sgolemon** 2015-06-23 22:13 UTC
Labels: do-not-reap
