### ISSUE TITLE
Debian build errors: PIC register clobbered

### ISSUE THREAD

**Issue by andbass** [facebook/folly#115] opened 2015-01-11 15:47 UTC
When trying to build on Debian Jessie, there is an assembly error in CpuId.h:
```
In file included from Bits.cpp:19:0:
./../folly/CpuId.h: In function 'int (* {anonymous}::folly_popcount_ifunc())(unsigned int)':
./../folly/CpuId.h:49:62: error: PIC register clobbered by 'ebx' in 'asm'
     __asm__("cpuid" : "=a"(n) : "a"(0) : "ebx", "edx", "ecx");
                                                              ^
./../folly/CpuId.h:51:65: error: PIC register clobbered by 'ebx' in 'asm'
       __asm__("cpuid" : "=c"(f1c_), "=d"(f1d_) : "a"(1) : "ebx");
                                                                 ^
./../folly/CpuId.h: In function 'int (* {anonymous}::folly_popcountll_ifunc())(long long unsigned int)':
./../folly/CpuId.h:49:62: error: PIC register clobbered by 'ebx' in 'asm'
     __asm__("cpuid" : "=a"(n) : "a"(0) : "ebx", "edx", "ecx");
                                                              ^
./../folly/CpuId.h:51:65: error: PIC register clobbered by 'ebx' in 'asm'
       __asm__("cpuid" : "=c"(f1c_), "=d"(f1d_) : "a"(1) : "ebx");
                                                                 ^
```
Here is a blog post that discusses PIC register clobbering in more detail: http://tuxion.com/2010/07/02/clobber-registers.html.

**Comment by Gownta** [comment] 2015-01-12 22:00
Could you put up a patch?

**Comment by andbass** [comment] 2015-01-13 03:26
I'm not very familiar with assembly, so I'm not sure if I can patch it myself. I'll give it a go however.

**Comment by ajz01** [comment] 2015-03-28 03:47
received the same error while trying to build proxygen which has folly dependency. Building from this repo directly produced the same error.

In file included from Bits.cpp:19:0:
./../folly/CpuId.h: In function 'int (* {anonymous}::folly_popcount_ifunc())(unsigned int)':
./../folly/CpuId.h:49:62: error: PIC register clobbered by 'ebx' in 'asm'
asm("cpuid" : "=a"(n) : "a"(0) : "ebx", "edx", "ecx");
^
./../folly/CpuId.h:51:65: error: PIC register clobbered by 'ebx' in 'asm'
asm("cpuid" : "=c"(f1c_), "=d"(f1d_) : "a"(1) : "ebx");

DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=17
DISTRIB_CODENAME=qiana
DISTRIB_DESCRIPTION="Linux Mint 17 Qiana"
NAME="Ubuntu"
VERSION="14.04, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04 LTS"
VERSION_ID="14.04"

gcc (Ubuntu 4.8.2-19ubuntu1) 4.8.2\

**Comment by facebook-github-bot-9** [comment] 2015-04-08 18:30
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by sindhya** [comment] 2015-05-11 05:51
Same error on 32-bit Ubuntu 14.04 LTS.
Doesn't occur on 64-bit version.!

**Comment by chipturner** [comment] 2015-06-04 18:55
Thank you for your patience. We're going to close out this issue. If you're still experiencing the problem described, please reopen the issue - thanks!

**Comment by chipturner** [comment] 2015-06-05 18:11
Hello!  This is a human.  My previous comment on this issue was a robot running amok.  I apologize that the issue was closed, and am re-opening it.  Thanks for your help with our folly project and for your understanding about rogue robots trying to take over the world.

**Comment by petrmanek** [comment] 2015-12-29 14:46
Any luck on this issue? I'm having the same problem.
(Debian Jessie 32-bit)

**Comment by philippv** [comment] 2015-12-30 02:47
Duplicate of https://github.com/facebook/folly/issues/103, folly requires 64-bit platform (https://github.com/facebook/folly/blob/master/folly/docs/Overview.md#compatibility).

**Closed by philippv** 2015-12-30 02:47 UTC
