### ISSUE TITLE
error: unknown type name 'ElfW'

### ISSUE THREAD

**Issue by yurivict** [facebook/folly#1338] opened 2020-03-14 00:50 UTC
Build breaks on FreeBSD:
```
work/glow-842f70c845aa22916d75baca56111c6fe03f64f8/thirdparty/folly/folly/experimental/symbolizer/Elf.h|38 col 17| error: unknown type name 'ElfW'
|| using ElfAddr = ElfW(Addr);
||                 ^
```

**Comment by yfeldblum** [comment] 2020-03-14 05:30
Duplicate of https://github.com/facebook/folly/pull/1317.

**Closed by yfeldblum** 2020-03-14 05:30 UTC
