### ISSUE TITLE
Does folly support Windows/MSVC now ?

### ISSUE THREAD

**Issue by pengweichu** [facebook/folly#405] opened 2016-04-26 14:11 UTC
Hello, i'm new to folly, our company consider using proxygen(which depends on folly) in our project, my question is: does folly support Windows/MSVS now ?

Thanks!

**Comment by Orvid** [comment] 2016-04-26 21:00
Not quite yet, no. I'm in the process of adding support to Folly for the newest update of MSVC 2015, but it's a long process.

**Comment by yfeldblum** [comment] 2016-08-14 06:13
Closing because this is a question and an answer, not a bug report.

**Closed by yfeldblum** 2016-08-14 06:13 UTC
