### ISSUE TITLE
 reference to 'thread' is ambiguous

### ISSUE THREAD

**Issue by nickdesaulniers** [facebook/folly#243] opened 2015-07-17 02:41 UTC
```
➜  folly git:(master) make
...
libtool: compile:  g++ -DHAVE_CONFIG_H -I./.. -pthread -I/usr/local/include -std=gnu++0x -g -O2 -MT io/async/ScopedEventBaseThread.lo -MD -MP -MF io/async/.deps/ScopedEventBaseThread.Tpo -c io/async/ScopedEventBaseThread.cpp  -fno-common -DPIC -o io/async/.libs/ScopedEventBaseThread.o
io/async/ScopedEventBaseThread.cpp:47:25: error: reference to 'thread' is ambiguous
  thread_ = make_unique<thread>(&EventBase::loopForever, &*eventBase_);
                        ^
./../folly/io/async/ScopedEventBaseThread.h:23:7: note: candidate found by name lookup is
      'std::thread'
class thread;
      ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/thread:259:24: note:
      candidate found by name lookup is 'std::__1::thread'
class _LIBCPP_TYPE_VIS thread
                       ^
io/async/ScopedEventBaseThread.cpp:47:25: error: reference to 'thread' is ambiguous
  thread_ = make_unique<thread>(&EventBase::loopForever, &*eventBase_);
                        ^
./../folly/io/async/ScopedEventBaseThread.h:23:7: note: candidate found by name lookup is
      'std::thread'
class thread;
      ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/thread:259:24: note:
      candidate found by name lookup is 'std::__1::thread'
class _LIBCPP_TYPE_VIS thread
                       ^
io/async/ScopedEventBaseThread.cpp:56:10: error: member access into incomplete type 'std::thread'
  thread_->join();
         ^
./../folly/io/async/ScopedEventBaseThread.h:23:7: note: forward declaration of 'std::thread'
class thread;
      ^
In file included from io/async/ScopedEventBaseThread.cpp:17:
In file included from ./../folly/io/async/ScopedEventBaseThread.h:19:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:2429:27: error:
      invalid application of 'sizeof' to an incomplete type 'std::thread'
            static_assert(sizeof(_Tp) > 0, "default_delete can not delete incomplete type");
                          ^~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:2630:13: note:
      in instantiation of member function 'std::__1::default_delete<std::thread>::operator()'
      requested here
            __ptr_.second()(__tmp);
            ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:2598:46: note:
      in instantiation of member function 'std::__1::unique_ptr<std::thread,
      std::__1::default_delete<std::thread> >::reset' requested here
    _LIBCPP_INLINE_VISIBILITY ~unique_ptr() {reset();}
                                             ^
io/async/ScopedEventBaseThread.cpp:26:24: note: in instantiation of member function
      'std::__1::unique_ptr<std::thread, std::__1::default_delete<std::thread> >::~unique_ptr'
      requested here
ScopedEventBaseThread::ScopedEventBaseThread(bool autostart) {
                       ^
./../folly/io/async/ScopedEventBaseThread.h:23:7: note: forward declaration of 'std::thread'
class thread;
      ^
In file included from io/async/ScopedEventBaseThread.cpp:20:
./../folly/Memory.h:43:37: error: allocation of incomplete type 'std::thread'
  return std::unique_ptr<T, Dp>(new T(std::forward<Args>(args)...));
                                    ^
io/async/ScopedEventBaseThread.cpp:47:13: note: in instantiation of function template specialization
      'folly::make_unique<std::thread, std::__1::default_delete<std::thread>, void
      (folly::EventBase::*)(), folly::EventBase *>' requested here
  thread_ = make_unique<thread>(&EventBase::loopForever, &*eventBase_);
            ^
./../folly/io/async/ScopedEventBaseThread.h:23:7: note: forward declaration of 'std::thread'
class thread;
      ^
5 errors generated.
make[2]: *** [io/async/ScopedEventBaseThread.lo] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

➜  folly git:(master) g++ -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)
Target: x86_64-apple-darwin14.3.0
Thread model: posix
```
osx 10.10.3
https://github.com/facebook/flint/issues/32

**Comment by fugalh** [comment] 2015-07-17 16:58
I'm not sure exactly what's going on, but the problem is that forward-declaring `std::thread` in the header and then doing `#include <thread>` in the implementation file, is not working with OSX's toolchain. The solution is to replace the forward declaration with `#include <thread>`

```
diff --git a/folly/io/async/ScopedEventBaseThread.h b/folly/io/async/ScopedEventBaseThread.h
index 60d62d7..fa35f35 100644
--- a/folly/io/async/ScopedEventBaseThread.h
+++ b/folly/io/async/ScopedEventBaseThread.h
@@ -17,12 +17,9 @@
 #pragma once
 
 #include <memory>
+#include <thread>
 #include <folly/io/async/EventBase.h>
 
-namespace std {
-class thread;
-}
-
 namespace folly {
 
 /**
```

I will fix this, but you can make the simple change immediately to get unblocked.

**Comment by entangledloops** [comment] 2016-08-03 19:13
Another solution is to wrap your forward declaration like this:
```
namsepace thread
{
  namespace __1
  {
    class thread;
  }
}
```

**Comment by yfeldblum** [comment] 2016-08-03 19:19
Or use the portability macros.

https://github.com/facebook/folly/blob/v2016.08.01.00/folly/Portability.h#L210-L220

**Comment by entangledloops** [comment] 2016-08-03 19:37
@yfeldblum Thanks, that header was informative. (I landed here researching the same error in a project unrelated to Folly.)

**Comment by Orvid** [comment] 2016-08-03 21:48
This was fixed, so closing it.

**Closed by Orvid** 2016-08-03 21:48 UTC
