### ISSUE TITLE
Traits.h doesn't compile with libstdc++ in debug mode

### ISSUE THREAD

**Issue by cieplik** [facebook/folly#942] opened 2018-09-28 17:50 UTC
Traits.h doesn't compile if used together with libstdc++ built in debug mode (`-D_GLIBCXX_DEBUG=1`). For example:

```
In file included from ./../folly/FBString.h:57:0,
                 from ./../folly/Demangle.h:19,
                 from ./../folly/Conv.h:40,
                 from Conv.cpp:16:
./../folly/Traits.h:546:9: note: candidates are: template<class T, class A> class std::vector
   class vector;
         ^
In file included from /usr/include/c++/5/vector:73:0,
                 from /usr/include/c++/5/bits/random.h:34,
                 from /usr/include/c++/5/random:49,
                 from /usr/include/c++/5/bits/stl_algo.h:66,
                 from /usr/include/c++/5/algorithm:62,
                 from ./../folly/Conv.h:26,
                 from Conv.cpp:16:
/usr/include/c++/5/debug/vector:111:11: note:                 template<class _Tp, class _Allocator> class std::__debug::vector
     class vector
```

**Comment by yfeldblum** [comment] 2018-09-29 20:34
It looks like this is missing the full error message from the compiler. This includes the notes that go along with the error message, but is missing the actual error.

**Comment by Quuxplusone** [comment] 2024-02-21 16:25
I believe this was caused by "Traits.h"'s forward-declaration of `std::vector`, and that it was fixed by the removal of that forward-declaration in cd5c885fc43a34a32c57c3840302b1435150ff8c. See the same error message and diagnosis/solution here too: https://github.com/ericniebler/range-v3/issues/857

I suggest this can be closed as resolved.

**Closed** 2024-02-21 19:51 UTC
